<template>
  <div class="page-shell max-w-4xl space-y-6"><header><p class="section-kicker">Metodologi</p><h1 class="mt-2 text-3xl font-bold">Cara tinjauan data bekerja</h1><p class="mt-4 text-sm leading-7 text-slate-600">Voyager menampilkan data bank yang tersedia dalam urutan kapitalisasi pasar dari penyedia data. Metode tiga faktor hanya dijelaskan untuk memahami laporan lama.</p></header>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Tujuan yang tersedia untuk riset baru</h2><p class="mt-3 text-sm leading-7">Bank: Tinjau data ROE dan P/BV bank IDX berkapitalisasi pasar terbesar pada periode yang tersedia.</p><p class="mt-3 text-sm leading-7 text-slate-600">Cakupan mengambil daftar bank dari penyedia data, mengurutkannya berdasarkan kapitalisasi pasar, lalu memeriksa delapan teratas. Metode tiga faktor tidak ditawarkan sebagai pilihan baru karena daftar perusahaannya tidak mewakili seluruh pasar.</p></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Tiga faktor aktif</h2><pre class="mt-4 overflow-x-auto rounded-xl bg-slate-50 p-4 text-xs leading-7">P = clamp(round(ROE × 4.2), 40, 100)
S = clamp(round((2.5 − min(2.5, D/E)) × 40), 30, 100)
V = clamp(round((35 − min(35, P/E)) × 3.5), 30, 100)
Q = round((0.25P + 0.20S + 0.20V) / 0.65)</pre><p class="mt-4 text-sm leading-7">Bobot efektif: profitabilitas 38,46%; solvabilitas 30,77%; valuasi 30,77%. P/BV positif merupakan syarat kelayakan, bukan komponen skor. Pertumbuhan dan konsistensi tidak memiliki skor.</p><p class="mt-4 rounded-xl bg-amber-50 p-4 text-sm leading-7 text-amber-950">Bobot belum dikalibrasi empiris dan tidak relatif sektor. FCF bukan faktor skor atau syarat positif: FCF negatif dapat menghasilkan Q=100. Skor ≥80 hanya memenuhi salah satu aturan shortlist.</p></section>
    <section data-testid="bank-methodology" class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Tinjauan data bank</h2><p class="mt-4 text-sm leading-7">Tinjauan memeriksa subsektor bank, kapitalisasi pasar dan harga positif, serta ketersediaan laba, ekuitas yang tidak nol, dan P/BV pada periode tahunan yang sama. Nilai ROE dan P/BV, termasuk nilai rendah atau negatif, tidak menentukan apakah bank ditampilkan.</p><p class="mt-4 rounded-xl bg-amber-50 p-4 text-sm leading-7 text-amber-950">ROE dihitung dari data penyedia, tetapi basis laba dan ekuitas dapat tidak cocok. P/BV historis belum diverifikasi terhadap tanggal harga dan jumlah saham.</p><details class="mt-4"><summary class="min-h-11 cursor-pointer text-sm font-semibold">Detail teknis</summary><p class="mt-2 font-mono text-xs">Kontrak: bank-evidence-contract-v1 · Formula: bank-evidence-v1</p></details></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Validitas input dan periode</h2><p class="mt-3 text-sm leading-7"><strong>Generic kompatibilitas:</strong> pendapatan, aset, ekuitas, kapitalisasi, harga, laba, P/E dan P/BV harus positif; debt ≥0; FCF serta provenance tersedia. ROE = laba/ekuitas ×100; ROA = laba/aset ×100; D/E = debt/ekuitas.</p><p class="mt-3 text-sm leading-7"><strong>Bank:</strong> subsektor harus Banks; market cap dan harga positif; earnings dan P/BV harus berupa angka finite; total equity harus finite dan tidak nol. Angka tidak wajib positif.</p><p class="mt-3 text-sm leading-7">FY finansial dan valuasi harus sama. Jika salah satu bank dalam top-eight kehilangan data wajib, laporan berstatus cannot_assess. Denominator memakai saldo akhir, bukan rata-rata. Pembulatan hanya pada tampilan.</p><p class="mt-3 text-sm leading-7">Pengambilan baru tidak berarti laporan keuangan atau harga baru. Benchmark P/BV peer tidak digunakan.</p></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Cara membaca hasil</h2><p class="mt-3 text-sm leading-7">Proses yang selesai tidak selalu berarti pertanyaan berhasil dijawab. Laporan membedakan data tersedia, tidak ada data kandidat, dan data wajib tidak lengkap.</p><p class="mt-3 text-sm leading-7">Bukti satu sumber belum diverifikasi independen. Ringkasan otomatis tidak tersedia. Periksa sumber asli, unit, perubahan laporan, periode keuangan, tanggal harga, dan waktu pengambilan. Laporan lama tidak otomatis menjadi benar karena metode sudah diperbarui.</p></section>
  </div>
</template>
