<template>
  <div class="page-shell max-w-4xl space-y-6"><header><p class="section-kicker">Metodologi</p><h1 class="mt-2 text-3xl font-bold">Cara tinjauan data bekerja</h1><p class="mt-4 text-sm leading-7 text-slate-600">Bank-evidence-v1 menampilkan data yang tersedia dan mempertahankan urutan market cap provider. Generic quality-3f-v2 tetap dijelaskan hanya untuk laporan lama.</p></header>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Tujuan yang tersedia untuk riset baru</h2><p class="mt-3 text-sm leading-7">Bank: Tinjau data ROE dan P/BV bank IDX berkapitalisasi pasar terbesar pada periode yang tersedia.</p><p class="mt-3 text-sm leading-7 text-slate-600">Cakupan mencakup delapan bank teratas dari structured screener provider dengan limit 50. Keanggotaan dan urutan mengikuti market cap provider selama data wajib tersedia. Generic tiga faktor tidak ditawarkan sebagai pilihan baru karena cakupan discovery-nya tidak representatif.</p></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Tiga faktor aktif</h2><pre class="mt-4 overflow-x-auto rounded-xl bg-slate-50 p-4 text-xs leading-7">P = clamp(round(ROE × 4.2), 40, 100)
S = clamp(round((2.5 − min(2.5, D/E)) × 40), 30, 100)
V = clamp(round((35 − min(35, P/E)) × 3.5), 30, 100)
Q = round((0.25P + 0.20S + 0.20V) / 0.65)</pre><p class="mt-4 text-sm leading-7">Bobot efektif: profitabilitas 38,46%; solvabilitas 30,77%; valuasi 30,77%. P/BV positif merupakan syarat kelayakan, bukan komponen skor. Pertumbuhan dan konsistensi tidak memiliki skor.</p><p class="mt-4 rounded-xl bg-amber-50 p-4 text-sm leading-7 text-amber-950">Bobot belum dikalibrasi empiris dan tidak relatif sektor. FCF bukan faktor skor atau syarat positif: FCF negatif dapat menghasilkan Q=100. Skor ≥80 hanya memenuhi salah satu aturan shortlist.</p></section>
    <section data-testid="bank-methodology" class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Tinjauan bank-evidence-v1</h2><p class="mt-4 text-sm leading-7">Tinjauan memeriksa subsektor Banks, market cap dan harga positif, serta ketersediaan earnings, equity nonzero, dan P/BV pada latest common FY. Nilai ROE dan P/BV, termasuk nilai rendah atau nonpositif, tidak menentukan keanggotaan. Urutan mengikuti market cap provider.</p><p class="mt-4 rounded-xl bg-amber-50 p-4 text-sm leading-7 text-amber-950">ROE berstatus provider-derived-unverified karena basis earnings dan equity dapat tidak cocok. P/BV historis provider belum terverifikasi basis tanggal dan sahamnya.</p></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Validitas input dan periode</h2><p class="mt-3 text-sm leading-7"><strong>Generic kompatibilitas:</strong> pendapatan, aset, ekuitas, kapitalisasi, harga, laba, P/E dan P/BV harus positif; debt ≥0; FCF serta provenance tersedia. ROE = laba/ekuitas ×100; ROA = laba/aset ×100; D/E = debt/ekuitas.</p><p class="mt-3 text-sm leading-7"><strong>Bank:</strong> subsektor harus Banks; market cap dan harga positif; earnings dan P/BV harus berupa angka finite; total equity harus finite dan tidak nol. Angka tidak wajib positif.</p><p class="mt-3 text-sm leading-7">FY finansial dan valuasi harus sama. Jika salah satu bank dalam top-eight kehilangan data wajib, laporan berstatus cannot_assess. Denominator memakai saldo akhir, bukan rata-rata. Pembulatan hanya pada tampilan.</p><p class="mt-3 text-sm leading-7">Pengambilan baru tidak berarti laporan keuangan atau harga baru. Benchmark P/BV peer tidak digunakan.</p></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Cara membaca hasil</h2><p class="mt-3 text-sm leading-7">Status proses COMPLETED berbeda dari tujuan terjawab. Laporan membedakan answered pada cakupan terbatas, not_answered saat tidak ada yang lolos, dan cannot_assess saat data belum dapat dinilai.</p><p class="mt-3 text-sm leading-7">Bukti satu sumber belum diverifikasi independen. Narasi AI laporan tidak tersedia. Periksa sumber asli, unit, restatement, FY, tanggal harga, dan waktu snapshot. Laporan lama tidak otomatis dinyatakan benar oleh formula baru.</p></section>
  </div>
</template>
