<template>
  <div class="page-shell max-w-4xl space-y-6"><header><p class="section-kicker">Metodologi</p><h1 class="mt-2 text-3xl font-bold">Cara screening bekerja</h1><p class="mt-4 text-sm leading-7 text-slate-600">Generic quality-3f-v2 memakai penilaian heuristik. Bank-filter-v1 hanya memeriksa kelayakan.</p></header>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Tujuan yang didukung</h2><p class="mt-3 text-sm leading-7">Generic: Screening IDX dengan ROE &gt;= 12%, Debt/Equity &lt;= 1.8x, dan skor tiga faktor &gt;= 80/100.</p><p class="mt-3 text-sm leading-7">Bank: Screening bank IDX berkapitalisasi pasar terbesar dengan subsektor Banks, latest common FY, ROE &gt;= 15%, dan P/BV &gt; 0.</p><p class="mt-3 text-sm leading-7 text-slate-600">Generic mencakup maksimal delapan simbol unik pertama sesuai urutan provider. Bank mencakup maksimal delapan bank berkapitalisasi pasar terbesar dari structured screener provider dengan limit 50. Yang berada di luar batas belum dinilai. Tidak ada filter indeks, pendalaman, dimensi tambahan, atau benchmark peer independen.</p></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Tiga faktor aktif</h2><pre class="mt-4 overflow-x-auto rounded-xl bg-slate-50 p-4 text-xs leading-7">P = clamp(round(ROE × 4.2), 40, 100)
S = clamp(round((2.5 − min(2.5, D/E)) × 40), 30, 100)
V = clamp(round((35 − min(35, P/E)) × 3.5), 30, 100)
Q = round((0.25P + 0.20S + 0.20V) / 0.65)</pre><p class="mt-4 text-sm leading-7">Bobot efektif: profitabilitas 38,46%; solvabilitas 30,77%; valuasi 30,77%. P/BV positif merupakan syarat kelayakan, bukan komponen skor. Pertumbuhan dan konsistensi tidak memiliki skor.</p><p class="mt-4 rounded-xl bg-amber-50 p-4 text-sm leading-7 text-amber-950">Bobot belum dikalibrasi empiris dan tidak relatif sektor. FCF bukan faktor skor atau syarat positif: FCF negatif dapat menghasilkan Q=100. Skor ≥80 hanya memenuhi salah satu aturan shortlist.</p></section>
    <section data-testid="bank-methodology" class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Filter bank-filter-v1</h2><p class="mt-4 text-sm leading-7">Filter memeriksa subsektor Banks, latest common FY, provider-derived simple ROE &gt;= 15%, dan P/BV &gt; 0. Kandidat yang lolos tetap dalam urutan market cap provider. Benchmark P/BV peer tidak digunakan.</p><p class="mt-4 rounded-xl bg-amber-50 p-4 text-sm leading-7 text-amber-950">ROE berstatus provider-derived-unverified dan P/BV adalah historical provider pada common FY. Basis earnings, equity, dan tanggal dapat tidak cocok. Hasil bukan penilaian kesehatan bank; lakukan uji tuntas independen.</p></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Validitas input dan periode</h2><p class="mt-3 text-sm leading-7"><strong>Generic:</strong> pendapatan, aset, ekuitas, kapitalisasi, harga, laba, P/E dan P/BV harus positif; debt ≥0; FCF serta provenance tersedia. ROE = laba/ekuitas ×100; ROA = laba/aset ×100; D/E = debt/ekuitas.</p><p class="mt-3 text-sm leading-7"><strong>Bank:</strong> subsektor harus Banks; earnings, total equity, dan P/BV harus positif. ROE sederhana diturunkan provider dari earnings / total equity dan belum terverifikasi.</p><p class="mt-3 text-sm leading-7">FY finansial dan valuasi harus sama. Data tidak lengkap berarti belum dapat dinilai, bukan gagal finansial. Denominator memakai saldo akhir, bukan rata-rata. Precision penuh digunakan untuk seleksi; pembulatan hanya pada tampilan.</p><p class="mt-3 text-sm leading-7">Pada formula generic, DuPont adalah identitas aljabar dari laporan yang sama, bukan verifikasi independen. FCF yield = FCF FY/kapitalisasi snapshot ×100 dan bukan faktor skor. Pengambilan baru tidak berarti laporan keuangan atau harga baru.</p></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Cara membaca hasil</h2><p class="mt-3 text-sm leading-7">Status proses COMPLETED berbeda dari tujuan terjawab. Laporan membedakan answered pada cakupan terbatas, not_answered saat tidak ada yang lolos, dan cannot_assess saat data belum dapat dinilai.</p><p class="mt-3 text-sm leading-7">Bukti satu sumber belum diverifikasi independen. Narasi AI laporan tidak tersedia. Periksa sumber asli, unit, restatement, FY, tanggal harga, dan waktu snapshot. Laporan lama tidak otomatis dinyatakan benar oleh formula baru.</p></section>
  </div>
</template>
