<script setup lang="ts">
import { computed } from 'vue'
import type { CandidateCompany } from '../types'
import { useResearchStore } from '../stores/researchStore'
import { evidenceStatusLabel, financialPeriodAge, formatDate, formatDateTime, sourceOriginLabel } from '../utils/presentation'
const props = defineProps<{ candidate: CandidateCompany }>()
const store = useResearchStore()
const bank = computed(() => props.candidate.formulaVersion === 'bank-evidence-v1')
const metric = (value: number | undefined, suffix = '') => Number.isFinite(value) ? `${value!.toLocaleString('id-ID', { maximumFractionDigits: 2 })}${suffix}` : 'Tidak tersedia'
</script>
<template>
  <article class="flex flex-col rounded-2xl border border-slate-200 bg-white p-5 sm:p-6">
    <header><p class="font-mono text-sm font-bold text-[#2F64A8]">#{{ candidate.rank }} · {{ candidate.symbol }}</p><h3 class="mt-1 text-lg font-bold">{{ candidate.name }}</h3><p class="mt-1 text-xs text-slate-500">{{ candidate.sector }}</p></header>
    <section class="mt-4"><h4 class="text-sm font-bold">{{ bank ? 'Mengapa data ini ditampilkan' : 'Mengapa perusahaan ini dipilih' }}</h4><p class="mt-2 text-sm leading-6 text-slate-600">{{ bank ? `Data ${candidate.symbol} tersedia pada ${candidate.financialPeriod || 'periode yang tersedia'} dan diurutkan berdasarkan kapitalisasi pasar dari penyedia data.` : candidate.whySelected }}</p></section>
    <section class="mt-4 rounded-xl bg-amber-50 p-3 text-sm leading-6 text-amber-950"><h4 class="font-bold">Basis yang perlu diverifikasi</h4><template v-if="bank"><p class="mt-1">ROE berasal dari earnings / total equity provider yang basisnya dapat tidak cocok. Basis tanggal dan saham P/BV historis provider belum terverifikasi.</p></template><ul v-else class="mt-1 list-disc pl-4"><li v-for="risk in candidate.potentialConcerns" :key="risk">{{ risk }}</li><li v-if="!candidate.potentialConcerns.length">Risiko spesifik belum tersedia; bukan berarti tidak ada risiko.</li></ul></section>
    <p v-if="financialPeriodAge(candidate.financialPeriod, store.report.timestamp)" class="mt-3 rounded-lg bg-amber-50 p-3 text-xs font-semibold leading-5 text-amber-950">{{ financialPeriodAge(candidate.financialPeriod, store.report.timestamp) }} Periksa laporan yang lebih baru sebelum membandingkan angka.</p>
    <dl class="mt-4 grid grid-cols-2 gap-3 text-xs leading-5"><div><dt class="text-slate-500">Periode keuangan</dt><dd>{{ candidate.financialPeriod || 'Tidak tersedia' }}</dd></div><div><dt class="text-slate-500">Harga per tanggal</dt><dd><time v-if="candidate.priceAsOf" :datetime="candidate.priceAsOf">{{ formatDate(candidate.priceAsOf) }}</time><template v-else>Tidak tersedia</template></dd></div><div><dt class="text-slate-500">Asal data</dt><dd>{{ sourceOriginLabel(candidate.sourceOrigin) }}</dd></div><div><dt class="text-slate-500">Diambil</dt><dd><time v-if="candidate.providerSource?.retrievedAt" :datetime="candidate.providerSource.retrievedAt">{{ formatDateTime(candidate.providerSource.retrievedAt) }}</time><template v-else>Tidak tersedia</template></dd></div></dl>
    <p class="mt-3 text-xs leading-5 text-slate-600">{{ evidenceStatusLabel(candidate.evidenceStatus) }}. {{ candidate.narrativeStatus === 'unavailable' ? 'Ringkasan otomatis tidak tersedia.' : 'Status ringkasan tidak tersedia.' }}</p>
    <details class="mt-4 border-t border-slate-200 pt-3"><summary class="min-h-11 cursor-pointer text-sm font-semibold">{{ bank ? 'Data ROE dan P/BV · lihat basis' : `Skor pendukung: ${metric(candidate.qualityScore)}/100 · lihat metrik` }}</summary><dl v-if="bank" class="mt-3 grid grid-cols-2 gap-3 text-xs"><div><dt>ROE dari data penyedia; basis belum diverifikasi</dt><dd>{{ metric(candidate.roePercent, '%') }}</dd></div><div><dt>P/BV historis; basis belum diverifikasi</dt><dd>{{ metric(candidate.pbvRatio, 'x') }}</dd></div><div><dt>Periode tahunan yang sama</dt><dd>{{ candidate.financialPeriod || 'Tidak tersedia' }}</dd></div><div><dt>Urutan data</dt><dd>#{{ candidate.rank }} berdasarkan kapitalisasi pasar</dd></div></dl><dl v-else class="mt-3 grid grid-cols-2 gap-3 text-xs"><div><dt>ROE</dt><dd>{{ metric(candidate.roePercent, '%') }}</dd></div><div><dt>P/E</dt><dd>{{ metric(candidate.peRatio, 'x') }}</dd></div><div><dt>Debt/Equity</dt><dd>{{ metric(candidate.debtToEquity, 'x') }}</dd></div><div><dt>FCF yield</dt><dd>{{ metric(candidate.freeCashFlowYieldPercent, '%') }}</dd></div></dl><p data-testid="metric-guide" class="mt-3 text-xs leading-5 text-slate-600"><template v-if="bank">Data ditampilkan sesuai urutan kapitalisasi pasar dari penyedia. Nilai ROE dan P/BV tidak menentukan apakah bank ditampilkan. Basis laba, ekuitas, tanggal, dan jumlah saham belum diverifikasi.</template><template v-else>{{ candidate.formulaVersion || 'Formula tidak tersedia' }}. Skor heuristik tiga faktor, bukan peluang untung atau tingkat keyakinan. FCF bukan faktor skor; FCF negatif tetap dapat memperoleh skor tinggi. FCF yield memakai FCF FY dan kapitalisasi snapshot.</template></p></details>
    <div class="mt-auto flex flex-wrap gap-2 pt-4 print:hidden"><button type="button" class="button-secondary" @click="store.openCandidateModal(candidate.symbol)">Ringkasan</button><router-link :to="`/research/${store.report.sessionId}/company/${candidate.symbol}`" class="button-secondary">Analisis lengkap</router-link></div>
  </article>
</template>
