<script setup lang="ts">
import { computed } from 'vue'
import type { CandidateCompany } from '../types'

type DossierItem = { label: string; value: string; context?: string }

const props = defineProps<{
  company: CandidateCompany
}>()

const trendItems = computed<DossierItem[]>(() => props.company.trends?.length ? props.company.trends.map(item => ({ label: item.label, value: `${item.value}`, context: `${item.period ? `${item.period} · ` : ''}Nilai indeks fixture ilustratif, bukan persentase.` })) : [
  { label: 'Pendapatan', value: `${props.company.revenue3yCagrPercent}% CAGR`, context: 'Rata-rata pertumbuhan tahunan selama tiga tahun.' },
  { label: 'Laba bersih', value: `${props.company.netIncome3yCagrPercent}% CAGR`, context: 'Rata-rata pertumbuhan tahunan selama tiga tahun.' }
])
</script>

<template>
  <section class="grid gap-5 lg:grid-cols-2" aria-label="Kinerja, tren, dan cakupan analisis">
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 class="text-lg font-bold text-slate-950">Kinerja dan tren</h2><div v-if="company.listingPerformance?.length" class="mt-4 grid gap-3 sm:grid-cols-2"><div v-for="item in company.listingPerformance" :key="item.label" class="rounded-xl bg-slate-50 p-4"><span class="text-xs text-slate-600">{{ item.label }}</span><strong class="mt-1 block font-mono text-lg">{{ item.value }}</strong><p v-if="item.detail" class="mt-2 text-xs leading-5 text-slate-500">{{ item.detail }}</p></div></div><div v-else class="mt-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4"><p class="text-sm font-semibold text-slate-800">Kinerja harga tidak tersedia</p><p class="mt-1 text-xs leading-5 text-slate-500">Fixture tidak memuat return harga, benchmark indeks, volatilitas, atau total shareholder return.</p></div><div class="mt-4 grid gap-3 sm:grid-cols-2"><div v-for="item in trendItems" :key="item.label" class="rounded-xl border border-slate-200 p-4"><span class="text-xs text-slate-600">{{ item.label }}</span><strong class="mt-1 block font-mono text-lg">{{ item.value }}</strong><p v-if="item.context" class="mt-2 text-xs leading-5 text-slate-500">{{ item.context }}</p></div></div></article>
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 class="text-lg font-bold text-slate-950">Segmen dan pandangan ke depan</h2><div v-if="company.segments?.length" class="mt-4 space-y-3"><div v-for="item in company.segments" :key="item.label" class="rounded-xl border border-slate-200 p-4"><div class="flex justify-between gap-3"><span class="text-sm font-semibold">{{ item.label }}</span><strong class="font-mono">{{ item.value }}</strong></div><p v-if="item.detail" class="mt-2 text-xs leading-5 text-slate-500">{{ item.detail }}</p></div></div><div v-else class="mt-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4"><p class="text-sm font-semibold text-slate-800">Rincian segmen tidak tersedia</p><p class="mt-1 text-xs leading-5 text-slate-500">Fixture tidak memuat kontribusi pendapatan, laba, atau geografi per segmen.</p></div><div v-if="company.forwardEstimates?.length" class="mt-4 space-y-3"><div v-for="item in company.forwardEstimates" :key="item.label" class="rounded-xl border border-slate-200 p-4"><div class="flex justify-between gap-3"><span class="text-sm font-semibold">{{ item.label }}</span><strong class="font-mono">{{ item.value }}</strong></div><p v-if="item.detail" class="mt-2 text-xs leading-5 text-slate-500">{{ item.detail }}</p></div></div><div v-else class="mt-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4"><p class="text-sm font-semibold text-slate-800">Estimasi forward tidak tersedia</p><p class="mt-1 text-xs leading-5 text-slate-500">Tidak ada panduan manajemen, estimasi analis, target harga, atau proyeksi laba dalam fixture.</p></div></article>
  </section>

  <section class="grid gap-5 lg:grid-cols-2" aria-label="Dividen, tata kelola, dan ESG">
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 class="text-lg font-bold text-slate-950">Dividen</h2><div class="mt-4 rounded-xl bg-slate-50 p-4"><span class="text-xs text-slate-600">Dividend yield fixture</span><strong class="mt-1 block font-mono text-2xl">{{ company.dividendYieldPercent }}%</strong></div><div v-if="company.dividendHistory?.length" class="mt-4 space-y-3"><div v-for="item in company.dividendHistory" :key="item.label" class="flex justify-between gap-3 border-b border-slate-100 pb-3 text-sm"><span>{{ item.label }}</span><strong class="font-mono">{{ item.value }}</strong></div></div><div v-else class="mt-4 rounded-xl border border-dashed border-slate-300 p-4"><p class="text-sm font-semibold text-slate-800">Riwayat dividen tidak tersedia</p><p class="mt-1 text-xs leading-5 text-slate-500">Yield saat ini tersedia, tetapi payout ratio, pertumbuhan dividen, tanggal pembayaran, dan histori tidak dimuat.</p></div></article>
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 class="text-lg font-bold text-slate-950">Tata kelola dan ESG</h2><div v-if="company.ownershipManagement?.length || company.esg?.length" class="mt-4 grid gap-3 sm:grid-cols-2"><div v-for="item in [...(company.ownershipManagement || []), ...(company.esg || [])]" :key="item.label" class="rounded-xl border border-slate-200 p-4"><span class="text-xs text-slate-600">{{ item.label }}</span><strong class="mt-1 block font-mono text-base">{{ item.value }}</strong><p v-if="item.detail" class="mt-2 text-xs leading-5 text-slate-500">{{ item.detail }}</p></div></div><div v-else class="mt-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4"><p class="text-sm font-semibold text-slate-800">Data tata kelola dan ESG tidak tersedia</p><p class="mt-1 text-xs leading-5 text-slate-500">Fixture tidak memuat struktur dewan, kepemilikan, kontroversi, emisi, target iklim, atau skor ESG. Risiko ESG dalam catatan kekhawatiran bersifat naratif, bukan penilaian terverifikasi.</p></div></article>
  </section>
</template>
