import assert from 'node:assert/strict'
import { localRuntime, waitFor } from './local-test-runtime.mjs'
const r = await localRuntime({ browser: true })
try {
  await r.navigate('/')
  await r.text('Belum ada riset tersimpan')
  assert.equal(await r.evaluate(`Boolean(document.querySelector('[data-testid="sidebar-active-session"]'))`), false)
  await r.navigate('/research/new')
  await r.text('Pilih tujuan secara eksplisit')
  assert.equal(await r.evaluate(`document.querySelector('[data-testid="preset-obj-consumer-growth"]').disabled`), true)
  await r.text('Pricing power, margin kotor, dan filter consumer belum didukung.')
  assert.equal(await r.evaluate(`document.querySelector('[data-testid="preset-obj-three-factor-screening"]').disabled`), true)
  await r.text('Tidak ditawarkan untuk riset baru')
  await r.evaluate(`document.querySelector('[data-testid="preset-obj-banking-moat"]').click()`)
  await r.text('Bank dengan ROE kuat untuk diteliti')
  await r.text('ROE terhitung >= 15%')
  await r.text('Maksimal delapan bank berkapitalisasi pasar terbesar')
  assert.equal(await r.evaluate(`document.querySelector('[data-testid="research-objective"]').value`), 'Screening bank IDX berkapitalisasi pasar terbesar dengan subsektor Banks, latest common FY, ROE >= 15%, dan P/BV > 0.')
  await waitFor(() => r.evaluate(`!document.querySelector('button[type="submit"]').disabled`), 'Template selection left submit locked')
  assert.equal(await r.evaluate(`document.querySelector('[data-testid="preset-obj-banking-moat"]').disabled`), false)
  const tokens = await r.evaluate(`(() => { const b = document.querySelector('button[type="submit"]'); b.focus(); const s = getComputedStyle(b); return { background: s.backgroundColor, outline: s.outlineWidth } })()`)
  assert.equal(tokens.background, 'rgb(47, 100, 168)')
  assert.equal(tokens.outline, '3px')
  await r.evaluate(`(() => { const field = document.querySelector('textarea'); field.value = 'Cari bank Indonesia yang sehat dan dividen berkelanjutan'; field.dispatchEvent(new Event('input', { bubbles: true })) })()`)
  await r.text('Tujuan belum didukung')
  assert.equal(await r.evaluate(`document.querySelector('button[type="submit"]').disabled`), true)
  await r.evaluate(`document.querySelector('[data-testid="preset-obj-banking-moat"]').click()`)
  await waitFor(() => r.evaluate(`!document.querySelector('button[type="submit"]').disabled`), 'Bank template did not unlock submit')
  const previewText = await r.evaluate(`document.querySelector('[data-testid="actual-universe"]').innerText`)
  assert.ok(previewText.includes('Belum tersedia'))
  assert.ok(!previewText.includes('914'))
  await r.evaluate(`document.querySelector('button[type="submit"]').click()`)
  await waitFor(() => r.evaluate(`Boolean(document.querySelector('[data-testid="session-next"]'))`), 'Actual backend pipeline did not publish')
  const id = await r.evaluate(`location.pathname.split('/')[2]`)
  assert.ok(id.startsWith('RES-'))
  const actual = (await r.request(`/research-sessions/${id}`)).data.session
  assert.ok(actual.candidates.every(c => c.subsector === 'Banks'))
  // Fresh browser-equivalent document: erase browser storage, then open deep link.
  await r.send('Storage.clearDataForOrigin', { origin: r.appUrl, storageTypes: 'all' })
  await r.navigate(`/research/${id}/report`)
  await r.text('Tujuan terjawab pada cakupan terbatas')
  assert.equal(await r.evaluate(`location.pathname`), `/research/${id}/report`)
  await r.text('Skor pendukung')
  await r.text('FY2025')
  await r.text('2026-09-09')
  const cardOrder = await r.evaluate(`(() => { const a = document.querySelector('article'); const t = a.innerText; return [t.indexOf('Mengapa perusahaan'), t.indexOf('Risiko yang'), t.indexOf('Periode keuangan'), t.indexOf('Skor pendukung')] })()`)
  assert.ok(cardOrder.every((value, index) => value >= 0 && (!index || value > cardOrder[index - 1])))
  assert.equal(await r.evaluate(`document.body.innerText.includes('HIGH') || document.body.innerText.includes('914') || document.body.innerText.includes('Data contoh')`), false)
  await r.evaluate(`document.querySelector('#report-tab-summary').focus()`)
  await r.send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'ArrowRight', code: 'ArrowRight' })
  await r.text('Dua faktor pendukung')
  assert.equal(await r.evaluate(`document.activeElement.id`), 'report-tab-candidates')
  const factors = await r.evaluate(`document.querySelector('#report-panel-candidates').innerText`)
  for (const expected of ['ROE', 'P/BV', '60%', '40%']) assert.ok(factors.includes(expected))
  assert.equal(/Debt\/Equity|FCF|P\/E|DuPont/.test(factors), false)
  await r.evaluate(`document.querySelector('#report-tab-summary').click()`)
  await r.evaluate(`const trigger = document.querySelector('#report-panel-summary article button'); trigger.focus(); trigger.click()`)
  await waitFor(() => r.evaluate(`document.querySelector('[data-testid="candidate-dialog"]').open`), 'Native dialog did not open')
  await r.send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27, nativeVirtualKeyCode: 27 })
  await r.send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27, nativeVirtualKeyCode: 27 })
  await waitFor(() => r.evaluate(`!document.querySelector('[data-testid="candidate-dialog"]').open`), 'Escape did not close modal')
  assert.equal(await r.evaluate(`document.activeElement.innerText`), 'Ringkasan')
  await r.evaluate(`Object.defineProperty(navigator.clipboard, 'writeText', { configurable: true, value: async text => { window.__copiedSummary = text } }); Array.from(document.querySelectorAll('button')).find(b => b.innerText === 'Salin ringkasan').click()`)
  await r.text('Ringkasan disalin.')
  assert.ok((await r.evaluate(`window.__copiedSummary`)).includes(id))
  await r.evaluate(`Object.defineProperty(navigator.clipboard, 'writeText', { configurable: true, value: async () => { throw new Error('Denied') } }); Array.from(document.querySelectorAll('button')).find(b => b.innerText === 'Salin ringkasan').click()`)
  await r.text('Ringkasan tidak dapat disalin.')
  // Native print/Ctrl+P must include all sections, every candidate and an A4 page.
  await r.send('Emulation.setEmulatedMedia', { media: 'print' })
  await r.evaluate(`window.dispatchEvent(new Event('beforeprint'))`)
  await waitFor(() => r.evaluate(`document.querySelectorAll('#report-panel-candidates article').length === ${actual.candidates.length}`), 'Print omitted a candidate')
  const printed = await r.evaluate(`(() => ({ title: getComputedStyle(document.querySelector('.report-page header')).display, panels: Array.from(document.querySelectorAll('[id^="report-panel-"]')).map(p => getComputedStyle(p).display), closedDetails: document.querySelectorAll('.report-page details:not([open])').length, text: document.querySelector('#report-panel-candidates').innerText }))()`)
  assert.notEqual(printed.title, 'none')
  assert.ok(printed.panels.every(display => display !== 'none'))
  assert.equal(printed.closedDetails, 0)
  for (const candidate of actual.candidates) assert.ok(printed.text.includes(candidate.symbol))
  const pdf = Buffer.from((await r.send('Page.printToPDF', { preferCSSPageSize: true, printBackground: true })).data, 'base64')
  assert.ok(pdf.subarray(0, 5).toString() === '%PDF-')
  const mediaBoxes = [...pdf.toString('latin1').matchAll(/\/MediaBox\s*\[\s*0\s+0\s+([\d.]+)\s+([\d.]+)\s*\]/g)]
  assert.ok(mediaBoxes.length > 0, 'No PDF pages')
  for (const box of mediaBoxes) { assert.ok(Math.abs(Number(box[1]) - 595.28) < 2); assert.ok(Math.abs(Number(box[2]) - 841.89) < 2) }
  await r.evaluate(`window.dispatchEvent(new Event('afterprint'))`)
  await r.send('Emulation.setEmulatedMedia', { media: '' })
  await waitFor(() => r.evaluate(`Boolean(document.querySelector('#report-tab-summary'))`), 'Print did not restore interactive report')
  // Force only the export HTTP response to fail; UI must not create a fallback Blob.
  let exportRequests = 0
  r.on('Fetch.requestPaused', event => {
    exportRequests++
    void r.send('Fetch.fulfillRequest', { requestId: event.requestId, responseCode: 503, responseHeaders: [{ name: 'Content-Type', value: 'application/json' }, { name: 'Access-Control-Allow-Origin', value: r.appUrl }], body: Buffer.from(JSON.stringify({ responseMessage: 'LOCAL export outage' })).toString('base64') })
  })
  await r.send('Fetch.enable', { patterns: [{ urlPattern: '*report/export*' }] })
  await r.evaluate(`window.__blobCalls = 0; const original = URL.createObjectURL; URL.createObjectURL = (...args) => { window.__blobCalls++; return original(...args) }; Array.from(document.querySelectorAll('summary')).find(s => s.innerText === 'Pilihan ekspor').click(); Array.from(document.querySelectorAll('button')).find(b => b.innerText === 'Unduh Markdown').click()`)
  await r.text('LOCAL export outage')
  assert.equal(exportRequests, 1)
  assert.equal(await r.evaluate(`window.__blobCalls`), 0)
  await r.send('Fetch.disable')
  // Bank preset uses its separate formula and never renders generic bank metrics.
  await r.navigate('/research/new')
  await r.text('Pilih tujuan secara eksplisit')
  await r.evaluate(`document.querySelector('[data-testid="preset-obj-banking-moat"]').click()`)
  await waitFor(() => r.evaluate(`!document.querySelector('button[type="submit"]').disabled`), 'Bank preset did not unlock submit')
  await r.evaluate(`document.querySelector('button[type="submit"]').click()`)
  await waitFor(() => r.evaluate(`Boolean(document.querySelector('[data-testid="session-next"]'))`), 'Bank pipeline did not publish')
  const bankId = await r.evaluate(`location.pathname.split('/')[2]`)
  const bank = (await r.request(`/research-sessions/${bankId}`)).data.session
  assert.deepEqual(bank.screeningFunnel[0].retainedSymbols, Array.from({ length: 8 }, (_, index) => `BANK${index + 1}`))
  await r.navigate(`/research/${bankId}/report`)
  await r.text('Tujuan terjawab pada cakupan terbatas')
  await r.evaluate(`document.querySelector('#report-tab-candidates').click()`)
  await r.text('bank-screen-2f-v1')
  await r.text('ROE · 60%')
  await r.text('P/BV · 40%')
  await r.text('P/BV')
  const bankReportText = await r.evaluate(`document.querySelector('.report-page').innerText`)
  for (const forbidden of ['Debt/Equity', 'FCF yield', 'Dekomposisi ROE DuPont', 'P/E Ratio', 'Capital-to-RWA', 'total capital', 'RWA', 'CAR', 'NPL', 'NIM', 'bank sehat', 'healthy bank']) assert.ok(!bankReportText.includes(forbidden), forbidden)
  // Start refusal retains the created session and releases busy; retry does not duplicate.
  const countBefore = (await r.request('/research-sessions')).data.sessions.length
  await r.navigate('/research/new')
  await r.text('Pilih tujuan secara eksplisit')
  await r.evaluate(`document.querySelector('[data-testid="preset-obj-banking-moat"]').click()`)
  await waitFor(() => r.evaluate(`!document.querySelector('button[type="submit"]').disabled`), 'Start-error form not ready')
  let startRequests = 0
  r.on('Fetch.requestPaused', event => {
    if (event.request.method === 'OPTIONS') { void r.send('Fetch.continueRequest', { requestId: event.requestId }); return }
    startRequests++; void r.send('Fetch.fulfillRequest', { requestId: event.requestId, responseCode: 503, responseHeaders: [{ name: 'Content-Type', value: 'application/json' }, { name: 'Access-Control-Allow-Origin', value: r.appUrl }], body: Buffer.from(JSON.stringify({ responseMessage: 'LOCAL start unavailable' })).toString('base64') })
  })
  await r.send('Fetch.enable', { patterns: [{ urlPattern: '*research-sessions/*/start' }] })
  await r.evaluate(`const b = document.querySelector('button[type="submit"]'); b.click(); b.click()`)
  await waitFor(() => r.evaluate(`Boolean(document.querySelector('[data-testid="objective-error"]'))`), 'Start error not shown')
  assert.ok((await r.evaluate(`document.querySelector('[data-testid="objective-error"]').innerText`)).includes('LOCAL start unavailable'), await r.evaluate(`document.querySelector('[data-testid="objective-error"]').innerText`))
  assert.equal(startRequests, 1)
  assert.equal(await r.evaluate(`document.querySelector('button[type="submit"]').disabled`), false)
  assert.equal((await r.request('/research-sessions')).data.sessions.length, countBefore + 1)
  await r.send('Fetch.disable')
  await r.evaluate(`document.querySelector('button[type="submit"]').click()`)
  await waitFor(() => r.evaluate(`Boolean(document.querySelector('[data-testid="session-next"]'))`), 'Retrying start did not publish')
  assert.equal((await r.request('/research-sessions')).data.sessions.length, countBefore + 1)
  // An authoritative retry snapshot clears old publication and candidates immediately.
  r.on('Fetch.requestPaused', event => {
    const session = { ...structuredClone(actual), revision: actual.revision + 1, status: 'UNDERSTANDING', publishedAttemptId: null, report: null, candidates: [], screeningFunnel: [], screening: [] }
    void r.send('Fetch.fulfillRequest', { requestId: event.requestId, responseCode: 200, responseHeaders: [{ name: 'Content-Type', value: 'application/json' }, { name: 'Access-Control-Allow-Origin', value: r.appUrl }], body: Buffer.from(JSON.stringify({ session })).toString('base64') })
  })
  await r.send('Fetch.enable', { patterns: [{ urlPattern: `${r.apiUrl}/api/v1/research-sessions/${id}` }] })
  await r.navigate(`/research/${id}/report`)
  await r.text('Laporan belum tersedia')
  assert.equal(await r.evaluate(`Boolean(document.querySelector('[data-testid="objective-status"]'))`), false)
  await r.send('Fetch.disable')
  // Mobile keeps material provenance and comparison limitations visible.
  await r.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
  await r.navigate(`/research/${id}/peers`)
  await r.text('Benchmark peer sektor belum didukung')
  assert.equal(await r.evaluate(`document.querySelector('[data-testid="relative-warning"]').getBoundingClientRect().height > 0`), true)
  assert.equal(await r.evaluate(`document.documentElement.scrollWidth <= innerWidth`), true)
  const profileCandidate = actual.candidates[0]
  await r.navigate(`/research/${id}/company/${profileCandidate.symbol}`)
  await r.text(`${profileCandidate.symbol} — ${profileCandidate.name}`)
  assert.equal(await r.evaluate(`document.documentElement.scrollWidth <= innerWidth`), true)
  assert.equal(await r.evaluate(`document.body.innerText.includes('Riset mendalam ${profileCandidate.symbol}')`), false)
  // Distinguish missing data from a genuine zero-result financial selection.
  await r.setMode('incomplete')
  const missing = await r.create(); await r.start(missing); await r.finish(missing.id)
  await r.navigate(`/research/${missing.id}/report`)
  await r.text('Tujuan belum dapat dinilai sepenuhnya')
  await r.text('berbeda dari gagal kriteria finansial')
  await r.setMode('none')
  const none = await r.create(); await r.start(none); await r.finish(none.id)
  await r.navigate(`/research/${none.id}/report`)
  await r.text('Tujuan belum terjawab: tidak ada kandidat lolos')
  // Missing candidate data must remain unavailable, including absent narrative.
  r.on('Fetch.requestPaused', event => {
    const session = structuredClone(actual)
    session.candidates = session.candidates.map(c => { delete c.sector; delete c.subsector; delete c.whySelected; delete c.potentialConcerns; delete c.keyStrengths; delete c.evidenceStatus; delete c.narrativeStatus; delete c.qualityScore; return c })
    void r.send('Fetch.fulfillRequest', { requestId: event.requestId, responseCode: 200, responseHeaders: [{ name: 'Content-Type', value: 'application/json' }, { name: 'Access-Control-Allow-Origin', value: r.appUrl }], body: Buffer.from(JSON.stringify({ session })).toString('base64') })
  })
  await r.send('Fetch.enable', { patterns: [{ urlPattern: `${r.apiUrl}/api/v1/research-sessions/${id}` }] })
  await r.navigate(`/research/${id}/report`)
  await r.text('Alasan pemilihan belum tersedia')
  await r.text('Status bukti tidak tersedia')
  assert.equal(await r.evaluate(`document.body.innerText.includes('Financials') || document.body.innerText.includes('HIGH') || document.body.innerText.includes('Arus kas sehat')`), false)
  await r.send('Fetch.disable')
  // Read outage is not a 404, and must not render another session's report.
  r.on('Fetch.requestPaused', event => { void r.send('Fetch.fulfillRequest', { requestId: event.requestId, responseCode: 503, responseHeaders: [{ name: 'Content-Type', value: 'application/json' }, { name: 'Access-Control-Allow-Origin', value: r.appUrl }], body: Buffer.from(JSON.stringify({ responseMessage: 'LOCAL read outage' })).toString('base64') }) })
  await r.send('Fetch.enable', { patterns: [{ urlPattern: `${r.apiUrl}/api/v1/research-sessions/${id}` }] })
  await r.navigate(`/research/${id}/report`)
  await r.text('Sesi belum dapat dimuat')
  assert.equal(await r.evaluate(`location.pathname`), `/research/${id}/report`)
  assert.equal(await r.evaluate(`Boolean(document.querySelector('[data-testid="objective-status"]'))`), false)
  await r.send('Fetch.disable')
  await r.navigate('/research/UNKNOWN/report')
  await r.text('Halaman tidak ditemukan')
  // Failed provider produces visible failure and no published report.
  await r.setMode('outage')
  const outage = await r.create(); await r.start(outage); const failed = await r.finish(outage.id)
  await r.navigate(`/research/${outage.id}`)
  await r.text(failed.attempts.at(-1).failureReason)
  assert.equal(await r.evaluate(`Boolean(document.querySelector('[data-testid="session-next"]'))`), false)
  await r.navigate('/company/UNSEEN')
  await r.text('HTTP 503')
  assert.equal(await r.evaluate(`document.body.innerText.includes('Perusahaan tidak ditemukan')`), false)
  await r.navigate(`/research/${id}/trace`)
  await r.text('Cakupan dan aturan yang diperiksa')
  assert.equal(await r.evaluate(`document.body.innerText.includes('Tool Calls') || document.body.innerText.includes('inputDigest')`), false)
  await r.navigate('/schedules')
  await r.text('Temukan dan lanjutkan riset Anda')
  assert.equal(await r.evaluate(`location.pathname`), '/research')
  assert.equal(await r.evaluate(`document.body.innerText.includes('prototype-fixture') || document.body.innerText.includes('sangat kuat dalam model')`), false)
  assert.deepEqual(r.exceptions, [], 'Unexpected browser runtime exceptions')
  console.log('LOCAL browser: real create/start/report, template lock, unsupported objective, fresh deep link, keyboard/modal, mobile provenance, no fake adapter/export, incomplete/empty/provider/read errors, 404 and trace removal passed.')
} finally { await r.close() }
